apiVersion: v1
kind: Service
metadata:
  name: waiter
spec:
  selector:
    app: waiter-service
  ports:
  - name: http
    port: 8080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: waiter-service-v1
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: waiter-service
        version: v1
    spec:
      containers:
      - name: waiter-service
        image: registry.cn-huhehaote.aliyuncs.com/digitalsonic/waiter-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: WAITER_NAME
          value: "Mark I"
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: waiter-service-v2
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: waiter-service
        version: v2
    spec:
      containers:
      - name: waiter-service
        image: registry.cn-huhehaote.aliyuncs.com/digitalsonic/waiter-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8080
        env:
        - name: WAITER_NAME
          value: "Mark II"
---
apiVersion: v1
kind: Service
metadata:
  name: customer
spec:
  selector:
    app: customer-service
  type: NodePort
  ports:
  - name: http
    port: 7080
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: customer-service
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: customer-service
        version: v1
    spec:
      containers:
      - name: customer-service
        image: registry.cn-huhehaote.aliyuncs.com/digitalsonic/customer-service
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 7080
